import tweepy
# AUTENTICAR AO TWITTER
auth = tweepy.OAuthHandler("api_key", "api_secret_key")
auth.set_access_token("access_token", "access_token_secret")


api = tweepy.API(auth)


print (" ")
print ("PT-BR - Esse é um script para tweetar usando a biblioteca Tweepy")
print ("EN - This is a script to tweet using the library Tweepy")
print (" ")
print ("By: luisgbr1el")
print (" ")
print ("O que deseja tweetar? | What do you want tweet?")
print ("[1] Texto | Text")
print ("[2] Imagem | Image")
print ("[3] Texto e Imagem | Text with Image")
num = input("Escolha a opção: | Choose the option: ")

if num == "1":
	tweet = input("Digite o texto: | Type the text: ")
	print (" ")
	print ("Texto: | Text: ")
	print (tweet)
	print (" ")
	print ("Tweetando mensagem... | Tweeting...")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	api.update_status(tweet)
	print ("Tweetado! | Tweeted!")

if num == "2":
	print ("Ponha a foto na minha pasta. | Put the image in my directory (this file directory)")
	print (" ")
	linkF = input("Digite o nome e a extensão da foto: (Ex: image.png) | Type the name and extension of the image: (Ex: image.png)")
	print (" ")
	print ("Imagem: | Image: ")
	print (linkF)
	print (" ")
	print ("Tweetando foto... | Tweeting image...")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	api.update_with_media(linkF)
	print ("Tweetado! | Tweeted!")

if num == "3":
	print ("Ponha a foto na minha pasta. | Put the image in my directory (this file directory)")
	print (" ")
	linkF = input("Digite o nome e a extensão da foto: (Ex: image.png) | Type the name and extension of the image: (Ex: image.png)")
	texto = input("Digite o texto para ir com a foto: | Type the text to tweet with the image")
	print (" ")
	print ("Tweet:")
	print (texto)
	print (linkF)
	print (" ")
	print ("Tweetando... | Tweeting...")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	print (" ")
	api.update_with_media(linkF, texto)
	print ("Tweetado! | Tweeted!")